version: "3.6"

services:
  db:
    container_name: 'brisum-golang-event_sourcing-postgres'
    image: postgres:13.2
    ports:
      - 5432:5432
    volumes:
      - brisum_golang_event_sourcing_postgres:/var/lib/postgresql/data
      - .docker/postgres/migration:/migration
    environment:
      - PGDATA:/var/lib/postgresql/data/data
    env_file:
      - .env

volumes:
  brisum_golang_event_sourcing_postgres: